// ===== Published complaints =====
// Complaints arrive by email from the /complaints/new form. To publish one,
// add it at the TOP of this list and deploy. Rules before adding one:
//  - never include the complainant's name, phone or email
//  - never name individual staff members ("a staff member" instead)
//  - keep it to what the customer says happened, in plain English
import type { Complaint } from "./complaints";

export const PUBLISHED_COMPLAINTS: Complaint[] = [
  {
    id: "google-ranchers-i8-stale-pizza",
    restaurant: "Ranchers",
    city: "Islamabad",
    area: "I-8",
    category: "Food quality",
    rating: 1,
    title: "Stale pizza, soggy fries and a flat soft drink",
    story:
      "I visited Ranchers I-8 last night and it was one of the most disappointing fast-food experiences I have had. The pizza was very poor quality: the crust was extremely hard and tasted stale. The loaded fries were drowned in ketchup, which ruined the flavour, and they did not taste fresh at all. To make it worse, the soft drink tasted old and flat.\n\nI expected much better from Ranchers. The food quality and freshness were far below standard, and I hope the management pays attention to quality control. I would not recommend this branch.\n\nFood: 1/5. Service: 1/5. Atmosphere: 1/5.",
    orderDate: "",
    source: "Google review",
    publishedAt: Date.UTC(2026, 8, 26, 17),
  },
  {
    id: "google-ranchers-i8-raw-krunch",
    restaurant: "Ranchers",
    city: "Islamabad",
    area: "I-8",
    category: "Food quality",
    rating: 1,
    title: "Undercooked Krunch burgers and no follow-up on the complaint",
    story:
      "I ordered two Krunch burgers from the I-8 branch. When I opened the pack at home, the chicken was not properly fried and the coating tasted of raw flour. There was no taste at all.\n\nI called the Ranchers customer service centre to complain. They told me the branch would call me to log the complaint, but the branch never called. Very poor customer care. I would not recommend it to anyone.\n\nFood: 1/5. Service: 1/5. Atmosphere: 1/5.",
    orderDate: "",
    source: "Google review",
    publishedAt: Date.UTC(2026, 8, 26, 16),
  },
  {
    id: "google-ranchers-burnt-wings",
    restaurant: "Ranchers",
    city: "Islamabad",
    area: "",
    category: "Food quality",
    rating: 1,
    title: "Burnt wings delivered",
    story:
      "Very disappointed with my order. The wings I received were clearly burnt and not acceptable to serve. This is not the quality I expected. I hope Ranchers improves its quality control and makes sure customers receive properly prepared food.",
    orderDate: "",
    source: "Google review",
    publishedAt: Date.UTC(2026, 8, 26, 15),
  },
  {
    id: "google-ranchers-food-poisoning",
    restaurant: "Ranchers",
    city: "Islamabad",
    area: "",
    category: "Hygiene",
    rating: 1,
    title: "Fell seriously ill after eating here",
    story:
      "After eating their food I had severe health problems that appeared to be food poisoning. This raises serious concerns about their food safety standards. There seems to be a lack of proper hygiene, quality control and food safety. The taste and quality of the food were also very poor, and the service was unacceptable.\n\nCustomers trust restaurants to maintain health and safety standards. I ask the management to review their food quality, hygiene and service before more customers are affected. If this is not addressed, I will consider reporting it to the health and food safety authorities. (Dine in.)",
    orderDate: "",
    source: "Google review",
    publishedAt: Date.UTC(2026, 8, 26, 14),
  },
  {
    id: "google-ranchers-beef-burger-object",
    restaurant: "Ranchers",
    city: "Islamabad",
    area: "",
    category: "Hygiene",
    rating: 1,
    title: "Found something disgusting inside my beef burger",
    story:
      "I ordered a beef burger and found something disgusting inside it, which completely ruined my meal. This is a serious hygiene issue and extremely unsafe to serve to customers. I will never order again and will not recommend this place to anyone.",
    orderDate: "",
    source: "Google review",
    publishedAt: Date.UTC(2026, 8, 26, 13),
  },
  {
    id: "google-ranchers-rude-unequal-treatment",
    restaurant: "Ranchers",
    city: "Islamabad",
    area: "",
    category: "Staff behaviour",
    rating: 1,
    title: "Rude staff and unequal treatment of customers",
    story:
      "By far the worst dining experience I have had. This was my first and definitely my last visit. The staff were rude and unprofessional, even though we placed a large order.\n\nWhen we arrived, the waiter asked if our order was for takeaway and told us to go and sit in a corner while it was prepared. There were four of us but we were only given three seats, so one of us had to stand. Then another couple arrived after us and were greeted warmly and treated with respect, while we received the opposite. That difference in treatment was unacceptable. I would not recommend this restaurant to anyone.",
    orderDate: "",
    source: "Google review",
    publishedAt: Date.UTC(2026, 8, 26, 12),
  },
  {
    id: "google-ranchers-slow-cold-pizzas",
    restaurant: "Ranchers",
    city: "Islamabad",
    area: "",
    category: "Slow service",
    rating: 1,
    title: "Pizzas arrived 30 minutes apart and cold food was never replaced",
    story:
      "We ordered four medium pizzas and loaded fries, but the service was slow and inattentive. The first two pizzas arrived promptly, but the other two took another 22 to 30 minutes, and the loaded fries took 20 minutes. When I complained that the food was cold, nobody listened. Despite repeated requests, nothing was replaced and we had to settle for cold food.\n\nThe food quality was also below par and affected our health later. It is frustrating to feel ignored as a customer. I will not be visiting again any time soon.",
    orderDate: "",
    source: "Google review",
    publishedAt: Date.UTC(2026, 8, 26, 11),
  },
  {
    id: "google-ranchers-packaging-cold-fries",
    restaurant: "Ranchers",
    city: "Islamabad",
    area: "",
    category: "Food quality",
    rating: 2,
    title: "Burgers stuck to the paper, unlabelled and with cold fries",
    story:
      "I ordered a deal and it was a disappointing experience. Instead of a proper foil wrapper, the burgers were wrapped in paper that stuck to the burger itself, which made them messy and unpleasant to eat. I ordered three different burgers but none were labelled, so we could not tell which was which. On top of that, the fries were cold when they arrived. The food quality and packaging did not meet expectations.",
    orderDate: "",
    source: "Google review",
    publishedAt: Date.UTC(2026, 8, 26, 10),
  },
  {
    id: "google-ranchers-mouldy-buns",
    restaurant: "Ranchers",
    city: "Islamabad",
    area: "",
    category: "Hygiene",
    rating: 1,
    title: "Mould on burger buns in a delivery order",
    story:
      "Today we bought a deal with four burgers. Two of them had mould on the lower bun, and the other two were only okay. We also ordered a separate burger, and its bun had green spots all over it. Your dine-in is good, but the delivered food is terrible. Your Fusion Cola also has no taste.",
    orderDate: "",
    source: "Google review",
    publishedAt: Date.UTC(2026, 8, 26, 9),
  },
  {
    id: "google-cheezious-f7-understaffed",
    restaurant: "Cheezious",
    city: "Islamabad",
    area: "F-7",
    category: "Slow service",
    rating: 2,
    title: "Understaffed, with a long wait for food and the bill",
    story:
      "A very disappointing experience at Cheezious F-7. The branch seemed understaffed and there was a clear lack of customer attention and management. Even for a simple bill I had to wait quite some time, while three different waiters came and asked about the bill again and again. The order also took much longer than expected.\n\nThe food itself was fine, but the service and management need to improve. Customers should get proper attention and timely service, especially when the restaurant is busy.\n\nFood: 4/5. Atmosphere: 5/5. (Dine in, group of 3 to 4, Rs. 2,000 to 3,000.)",
    orderDate: "",
    source: "Google review",
    publishedAt: Date.UTC(2026, 8, 5),
  },
  {
    id: "google-cheezious-f7-takeaway",
    restaurant: "Cheezious",
    city: "Islamabad",
    area: "F-7 (new branch)",
    category: "Food quality",
    rating: 1,
    title: "Takeaway food was so poor it went to waste",
    story:
      "I visited your new F-7 branch today and placed a takeaway order at 3:45 PM, but the quality was very bad. We were in a hurry and took it anyway, but the food ended up being wasted. Please look into this.",
    orderDate: "",
    source: "Google review",
    publishedAt: Date.UTC(2026, 8, 26, 5),
  },
  {
    id: "google-cheezious-f7-burnt-pizza",
    restaurant: "Cheezious",
    city: "Islamabad",
    area: "F-7",
    category: "Food quality",
    rating: 1,
    title: "Burnt pizza and wings with an unpleasant smell",
    story:
      "I visited the F-7 branch between 9:00 PM and 9:45 PM and ordered pizza and wings. The experience was very disappointing. The food was overcooked and tasted burnt, and the pizza had an unpleasant smell, like an old frying pan. I had a foreign guest with me and it left a very bad impression. I have had the same items at the I-8 branch before and the quality there was much better, but at F-7 the food quality was extremely poor.\n\nFood: 1/5. Service: 2/5. Atmosphere: 3/5. (Dine in, Rs. 2,000 to 2,500.)",
    orderDate: "",
    source: "Google review",
    publishedAt: Date.UTC(2026, 8, 26, 4),
  },
  {
    id: "google-shahg-slow-rude-staff",
    restaurant: "Shah G Foods",
    city: "Islamabad",
    area: "",
    category: "Staff behaviour",
    rating: 1,
    title: "Very slow service and rude staff",
    story:
      "The service is very bad and very slow. The staff are rude. They bring your order hours late and then behave as if they are doing you a favour. Terrible.\n\nFood: 1/5. Service: 1/5. Atmosphere: 1/5. (Dine in, lunch.)",
    orderDate: "",
    source: "Google review",
    publishedAt: Date.UTC(2026, 6, 26),
  },
  {
    id: "google-shahg-breakfast-overcharged",
    restaurant: "Shah G Foods",
    city: "Islamabad",
    area: "",
    category: "Overcharging",
    rating: 2,
    title: "30 minute wait for breakfast, then double prices",
    story:
      "We went for breakfast and ordered parathas and fried eggs. We waited 30 minutes and they still did not serve us. There was only one waiter at the back and his attitude was dismissive. We reminded him three or four times but he did not bother to respond. In the end, a man from a neighbouring food stall took our order and brought the eggs and parathas from there.\n\nTo our surprise, the prices of eggs, parathas and tea were double the market rate. A simple fried egg was Rs. 60, when it is Rs. 30 at other restaurants, and the same went for other items.\n\nAtmosphere: 7/10. Food: 3/10.",
    orderDate: "",
    source: "Google review",
    publishedAt: Date.UTC(2026, 8, 26, 2),
  },
  {
    id: "google-shahg-thin-seekh-kabab",
    restaurant: "Shah G Foods",
    city: "Islamabad",
    area: "",
    category: "Food quality",
    rating: 1,
    title: "Poor service, no hygiene and paper-thin seekh kebab",
    story:
      "Third-class service and no hygiene. I ordered chicken seekh kebab, and what they served was as thin as tissue paper fried on a skewer, very low in quality. Their excuse was that chicken kebabs are always thin, as if it was my first time eating one. Wasted money.\n\n(Dine in, dinner, Rs. 500 to 1,000.)",
    orderDate: "",
    source: "Google review",
    publishedAt: Date.UTC(2026, 8, 26, 1),
  },
  {
    id: "2026-07-14-shahg-g8",
    restaurant: "Shah G Foods",
    city: "Islamabad",
    area: "G-8 Markaz",
    category: "Staff behaviour",
    rating: 1,
    title: "Rude and abusive staff behaviour",
    story:
      "My colleagues and I are regular customers at this branch, and today was the second time this has happened. A staff member behaved abusively towards us simply because we asked him to clear the waste and dirty dishes left by another table from our table. He was extremely rude, did not clear anything, and was ready to start a fight until other customers stopped him.\\n\\nOur order: Daal Chawal, lobia, roti and a cold drink (Rs. 1,160, paid in cash).",
    orderDate: "14 Jul 2026",
    publishedAt: Date.UTC(2026, 6, 14),
  },
];
